apiVersion: kude.kfirs.com/v1alpha1
kind: Pipeline
resources:
  - gcp-iam-service-account.yaml
  - pod-monitor.yaml
pipeline:
  - image: ghcr.io/arikkfir/kude/functions/create-namespace
    config:
      name: cert-manager
  - image: ghcr.io/arikkfir/kude/functions/helm
    network: true
    config:
      helm-version: 3.8.1
      args:
        - template
        - cert-manager
        - cert-manager
        - --include-crds
        - --namespace=cert-manager
        - --repo=https://charts.jetstack.io
        - --version=1.8.0
        - --values=/workspace/values.yaml
    mounts:
      - cert-manager-values.yaml:values.yaml
  - image: ghcr.io/arikkfir/kude/functions/yq
    config:
      expr: |-
        . |= with(
          select(.apiVersion == "apps/v1" and
                 .kind == "Deployment" and
                 .metadata.name == "cert-manager");
          .spec.template.spec.containers[0].ports[0].name = "metrics"
        )
  - image: ghcr.io/arikkfir/kude/functions/set-namespace
    config:
      namespace: cert-manager
