apiVersion: monitoring.gke.io/v1alpha1
kind: PodMonitor
metadata:
  name: cert-manager
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cert-manager
      app.kubernetes.io/component: controller
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      scheme: http
      interval: 10s
