apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- https://github.com/argoproj/argo-cd//manifests/cluster-install?ref=v2.6.7&timeout=300s
- argocd-server-rbac-clusterrole.yaml
- argocd-server-rbac-clusterrolebinding.yaml

patches:
  - target:
      kind: ConfigMap
      name: argocd-cm
    path: argocd-cm-patch.yaml
  - target:
      kind: ConfigMap
      name: argocd-cmd-params-cm
    path: argocd-cmd-params-cm-patch.yaml
