apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: ArgoCD project, used for grouping ArgoCD-related applications.
  destinations:
    - server: https://kubernetes.default.svc
      namespace: argocd
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  orphanedResources:
    warn: true
    ignore:
      - group: argoproj.io
        kind: AppProject
        name: default
      - group: argoproj.io
        kind: AppProject
        name: argocd
      - group: argoproj.io
        kind: Application
        name: argocd
  sourceRepos:
    - https://github.com/arikkfir/infrastructure.git
  sourceNamespaces:
    - argocd
