apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: delivery
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Continuous Delivery project.
  destinations:
    - server: https://kubernetes.default.svc
      namespace: "!kube-system,!argocd,*"
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: true
  sourceRepos:
    - https://github.com/arikkfir/delivery.git
  sourceNamespaces:
    - '!kube-system,!argocd,*'
