kind: AppProject
apiVersion: argoproj.io/v1alpha1
metadata:
  name: environments
  namespace: argocd
spec:
  description: Environment-specific applications.
  destinations:
    - server: https://kubernetes.default.svc
      namespace: "env-*"
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: true
  sourceRepos:
    - https://github.com/arikkfir/delivery.git
  sourceNamespaces:
    - 'env-*'
