apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  interval: 5m
  chart:
    spec:
      chart: cert-manager
      version: v1.5.3
      sourceRef:
        kind: HelmRepository
        name: jetstack
  values:
    installCRDs: true
    prometheus:
      servicemonitor:
        enabled: false
    serviceAccount:
      annotations:
        iam.gke.io/gcp-service-account: cert-manager@arikkfir.iam.gserviceaccount.com
    resources:
      requests:
        cpu: 100m
        memory: 50Mi
      limits:
        cpu: 100m
        memory: 50Mi
    webhook:
      resources:
        requests:
          cpu: 100m
          memory: 50Mi
        limits:
          cpu: 100m
          memory: 50Mi
    cainjector:
      resources:
        requests:
          cpu: 100m
          memory: 50Mi
        limits:
          cpu: 100m
          memory: 50Mi
    startupapicheck:
      resources:
        requests:
          cpu: 100m
          memory: 50Mi
        limits:
          cpu: 100m
          memory: 50Mi
