apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  interval: 5m
  chart:
    spec:
      chart: cert-manager
      version: v1.6.1
      sourceRef:
        kind: HelmRepository
        name: jetstack
  postRenderers:
    - kustomize:
        patchesJson6902:
          - target:
              group: apps
              version: v1
              kind: Deployment
              name: cert-manager
            patch:
              - op: add
                path: /spec/template/spec/containers/0/ports/0/name
                value: metrics
  values:
    installCRDs: true
    serviceAccount:
      annotations:
        iam.gke.io/gcp-service-account: cert-manager@arikkfir.iam.gserviceaccount.com
    resources:
      requests:
        cpu: 100m
        memory: 50Mi
      limits:
        cpu: 100m
        memory: 50Mi
    prometheus:
      enabled: true
      servicemonitor:
        enabled: false
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kfirs.com/workload-nodes
              operator: Exists
    tolerations:
    - key: kfirs.com/workload-nodes
      operator: Exists
    webhook:
      resources:
        requests:
          cpu: 50m
          memory: 50Mi
        limits:
          cpu: 50m
          memory: 50Mi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kfirs.com/workload-nodes
                operator: Exists
      tolerations:
      - key: kfirs.com/workload-nodes
        operator: Exists
      serviceAccount:
        annotations:
          iam.gke.io/gcp-service-account: cert-manager@arikkfir.iam.gserviceaccount.com
    cainjector:
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
        limits:
          cpu: 100m
          memory: 150Mi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kfirs.com/workload-nodes
                operator: Exists
      tolerations:
      - key: kfirs.com/workload-nodes
        operator: Exists
      serviceAccount:
        annotations:
          iam.gke.io/gcp-service-account: cert-manager@arikkfir.iam.gserviceaccount.com
    startupapicheck:
      resources:
        requests:
          cpu: 100m
          memory: 50Mi
        limits:
          cpu: 100m
          memory: 50Mi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kfirs.com/workload-nodes
                operator: Exists
      tolerations:
      - key: kfirs.com/workload-nodes
        operator: Exists
      serviceAccount:
        annotations:
          iam.gke.io/gcp-service-account: cert-manager@arikkfir.iam.gserviceaccount.com
