apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - namespace.yaml
  - helm-jetstack-repository.yaml
  - helm-cert-manager-release.yaml
  - gcp-service-account.yaml
