apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - namespace.yaml
  - helm-repositories.yaml
  - helm-releases.yaml
  - gcp-service-account.yaml
  - pod-monitor.yaml
