apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets-controller
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: sealed-secrets
      version: 1.15.0-r1
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
  values:
    resources:
      limits:
        cpu: 500m
        memory: 100Mi
      requests:
        cpu: 200m
        memory: 100Mi
    crd:
      keep: true
