name: Setup Google Cloud SDK
description: Downloads & installs Google Cloud SDK on a clean Ubuntu container
inputs:
  service_account:
    description: Service account to authenticate as
    required: false
  version:
    description: Google Cloud SDK version
    required: false
    default: "367.0.0"
runs:
  using: composite
  steps:
    - name: Install dependencies
      run: apt-get update && apt-get install -y curl python3
      shell: bash
      env:
        DEBIAN_FRONTEND: noninteractive
    - name: Download & extract
      run: |-
        curl -sSL https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-${{ inputs.version }}-linux-x86_64.tar.gz | tar xz -C /usr/local
      shell: bash
    - name: Install
      run: |-
        /usr/local/google-cloud-sdk/install.sh --quiet --additional-components kubectl kustomize
        pushd /usr/local/google-cloud-sdk/bin \
          && ln -s $(pwd)/bq \
                   $(pwd)/docker-credential-gcloud \
                   $(pwd)/gcloud \
                   $(pwd)/gsutil \
                   $(pwd)/kubectl \
                   $(pwd)/kustomize \
                   /usr/local/bin/ \
          && popd
      shell: bash
    - name: Authenticate
      uses: google-github-actions/auth@v0.4.0
      if: ${{ inputs.service_account != '' }}
      with:
        workload_identity_provider: projects/8909046976/locations/global/workloadIdentityPools/github-actions/providers/default
        service_account: ${{ inputs.service_account }}
