name: Setup FluxCD
description: Downloads & installs FluxCD
runs:
  using: composite
  steps:
    - name: Install dependencies
      run: apt-get update && apt-get install -y curl
      shell: bash
      env:
        DEBIAN_FRONTEND: noninteractive
    - name: Install
      run: curl -s https://fluxcd.io/install.sh | bash
      shell: bash
