apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: devbot
spec:
  interval: 5m
  chart:
    spec:
      chart: devbot
      sourceRef:
        kind: GitRepository
        namespace: system
        name: flux-system
  values:
    api:
      serviceAccount:
        gcpWorkloadIdentityProject: arikkfir
      image:
        tag: abc123
      tolerations:
        - key: kfirs.com/workload-nodes
          operator: Exists
    portal:
      serviceAccount:
        gcpWorkloadIdentityProject: arikkfir
      image:
        tag: abc456
      tolerations:
        - key: kfirs.com/workload-nodes
          operator: Exists
    ingress:
      enabled: true
      dns:
        record:
          name: devbot.main.kfirs.com
          type: CNAME
          zone:
            namespace: system
            name: kfirs-com
          rrdatas:
            - traefik.kfirs.com
        certificate:
          issuerRef:
            kind: ClusterIssuer
            name: google-clouddns
#    affinity:
#      nodeAffinity:
#        requiredDuringSchedulingIgnoredDuringExecution:
#          nodeSelectorTerms:
#            - matchExpressions:
#                - key: kfirs.com/workload-nodes
#                  operator: Exists
---
