apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSManagedZone
metadata:
  annotations:
    cnrm.cloud.google.com/deletion-policy: abandon
  name: kfirs-com
spec:
  description: "kfirs.com DNS zone"
  dnsName: "kfirs.com."
