apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: system
resources:
- gotk-components.yaml
- gotk-sync.yaml
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
    path: gotk-patches.yaml
