apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
patches:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: helm-controller
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: 500m
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: 128Mi
- target:
    group: apps
    version: v1
    kind: Deployment
    name: kustomize-controller
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: 500m
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: 128Mi
- target:
    group: apps
    version: v1
    kind: Deployment
    name: notification-controller
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: 500m
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: 128Mi
- target:
    group: apps
    version: v1
    kind: Deployment
    name: source-controller
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: 500m
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: 256Mi
