apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
spec:
  interval: 30m
  chart:
    spec:
      chart: grafana
      version: 6.16.10
      sourceRef:
        kind: HelmRepository
        name: grafana-community
  valuesFrom:
    - kind: ConfigMap
      name: grafana
      optional: false
      valuesKey: grafana-values.yaml
