apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: secrets-store-csi-driver
spec:
  interval: 5m
  chart:
    spec:
      chart: secrets-store-csi-driver
      version: "1.0.0"
      sourceRef:
        kind: HelmRepository
        name: secrets-store-csi-driver
  values:
    logFormatJSON: true
    syncSecret:
      enabled: true
    enableSecretRotation: true
    rotationPollInterval: 2m
