apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets-controller
spec:
  interval: 5m
  chart:
    spec:
      chart: csi-secrets-store
      version: 1.0.0
      sourceRef:
        kind: HelmRepository
        name: secrets-store-csi-driver
  values:
    logFormatJSON: true
    syncSecret:
      enabled: true
    enableSecretRotation: true
    rotationPollInterval: 2m
