apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: devbot
spec:
  interval: 5m
  chart:
    spec:
      chart: devbot
      version: non-existent-version
      sourceRef:
        kind: HelmRepository
        namespace: system
        name: arikkfir
  values:
    api:
      serviceAccount:
        gcpWorkloadIdentityProject: arikkfir
      tolerations:
        - key: kfirs.com/workload-nodes
          operator: Exists
    portal:
      serviceAccount:
        gcpWorkloadIdentityProject: arikkfir
      tolerations:
        - key: kfirs.com/workload-nodes
          operator: Exists
    ingress:
      enabled: true
      dns:
        record:
          name: devbot.cluster.local
          type: CNAME
          zone:
            namespace: system
            name: kfirs-com
          rrdatas:
            - traefik.kfirs.com
        certificate:
          issuerRef:
            kind: ClusterIssuer
            name: google-clouddns
