apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-server
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    repoURL: https://github.com/arikkfir/infrastructure.git
    path: argocd/server
    targetRevision: HEAD
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: platform
  syncPolicy:
    automated:
      prune: true
      allowEmpty: false
      selfHeal: false # TODO: check if UI shows drift instead
