name: Setup Helm
description: Downloads & installs Helm
inputs:
  version:
    description: Helm version
    required: false
    default: v3.7.2
runs:
  using: composite
  steps:
    - name: Install dependencies
      run: apt-get update && apt-get install -y curl
      shell: bash
      env:
        DEBIAN_FRONTEND: noninteractive
    - name: Install
      run: curl -sSL "${URL}" | tar xzf - -C /tmp && mv /tmp/linux-amd64/helm /usr/local/bin/
      shell: bash
      env:
        URL: https://get.helm.sh/helm-${{ inputs.version }}-linux-amd64.tar.gz
