apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: platform
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./platform
  prune: true
  sourceRef:
    kind: GitRepository
    name: delivery
