apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: delivery
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
    url: https://github.com/arikkfir/delivery.git
