apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dns
resources:
  - namespace.yaml
  - gcp-dns-kfirfamily-com.yaml
  - gcp-dns-kfirs-com.yaml
  - gcp-dns-yellow-mint-com.yaml
