apiVersion: monitoring.gke.io/v1alpha1
kind: PodMonitor
metadata:
  name: helm-controller
spec:
  selector:
    matchLabels:
      app: helm-controller
  podMetricsEndpoints:
  - port: http-prom
    path: /metrics
    scheme: http
    interval: 10s
---
apiVersion: monitoring.gke.io/v1alpha1
kind: PodMonitor
metadata:
  name: kustomize-controller
spec:
  selector:
    matchLabels:
      app: kustomize-controller
  podMetricsEndpoints:
    - port: http-prom
      path: /metrics
      scheme: http
      interval: 10s
---
apiVersion: monitoring.gke.io/v1alpha1
kind: PodMonitor
metadata:
  name: notification-controller
spec:
  selector:
    matchLabels:
      app: notification-controller
  podMetricsEndpoints:
    - port: http-prom
      path: /metrics
      scheme: http
      interval: 10s
---
apiVersion: monitoring.gke.io/v1alpha1
kind: PodMonitor
metadata:
  name: source-controller
spec:
  selector:
    matchLabels:
      app: source-controller
  podMetricsEndpoints:
    - port: http-prom
      path: /metrics
      scheme: http
      interval: 10s
