apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: system
resources:
  - cnrm.yaml
  - cert-manager.yaml
  - https://raw.githubusercontent.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/main/deploy/provider-gcp-plugin.yaml
  - secrets-store-csi-driver.yaml
  - traefik.yaml
configurations:
  - kustomizeconfig.yaml
patches:
  - target:
      group: apps
      version: v1
      kind: DaemonSet
      labelSelector: app=csi-secrets-store-provider-gcp
    patch: |-
      - op: add
        path: /spec/template/spec/tolerations
        value:
          - key: kfirs.com/workload-nodes
            operator: Exists
