apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: secrets-store-csi-driver
spec:
  interval: 1h
  url: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: secrets-store-csi-driver
spec:
  interval: 5m
  chart:
    spec:
      chart: secrets-store-csi-driver
      version: "1.0.0"
      sourceRef:
        kind: HelmRepository
        name: secrets-store-csi-driver
  values:
    logFormatJSON: true
    syncSecret:
      enabled: true
    enableSecretRotation: true
    rotationPollInterval: 2m
    linux:
      tolerations:
        - key: kfirs.com/workload-nodes
          operator: Exists
