apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: traefik
spec:
  interval: 1h
  url: https://helm.traefik.io/traefik
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeAddress
metadata:
  name: traefik-ingress
spec:
  addressType: EXTERNAL
  description: GKE Ingress
  ipVersion: IPV4
  location: europe-west3
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: 10.6.2
      sourceRef:
        kind: HelmRepository
        name: traefik
  values:
    # Reference can be found at: https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
    logs:
      general:
        level: WARN
      access:
        enabled: true
        format: json
        bufferingSize: 0
        fields:
          general:
            defaultmode: keep
          headers:
            defaultmode: true
    metrics:
      prometheus:
        entryPoint: metrics
    service:
      enabled: true
      type: LoadBalancer
      spec:
        loadBalancerIP: 34.141.22.31
        externalTrafficPolicy: Local
      loadBalancerSourceRanges: [ 89.138.98.41/32 ]
    ingressRoute:
      dashboard:
        enabled: false
    resources:
      requests:
        cpu: 100m
        memory: 50Mi
      limits:
        cpu: 300m
        memory: 150Mi
    tolerations:
      - key: kfirs.com/workload-nodes
        operator: Exists
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kfirs.com/workload-nodes
                  operator: Exists
---
apiVersion: monitoring.gke.io/v1alpha1
kind: PodMonitor
metadata:
  name: traefik
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: traefik
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      scheme: http
      interval: 10s
