apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: traefik
spec:
  dependsOn:
    - name: cert-manager-issuer
    - name: cnrm-system
    - name: kfirs-com
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./kubernetes/manifests/traefik
  prune: true
  validation: client
