{{- $component := "portal" -}}
{{- $name := print .Chart.Name "-" .Release.Name "-" $component -}}
{{- $image := .Values.portal.image -}}
{{- $defaultServiceAccountName := ternary $name "default" .Values.portal.serviceAccount.create -}}
{{- $serviceAccountName := default $defaultServiceAccountName .Values.portal.serviceAccount.name -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: {{ .Chart.Name | quote }}
    helm.sh/chart: {{ print .Chart.Name "-" .Chart.Version | replace "+" "_" | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/component: {{ $component | quote }}
  name: {{ $name | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name | quote }}
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
      app.kubernetes.io/component: {{ $component | quote }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        app.kubernetes.io/component: {{ $component | quote }}
    spec:
      containers:
        - image: {{ print $image.repository ":" $image.tag | quote }}
          name: {{ $component | quote }}
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 9000
              name: metrics
              protocol: TCP
            - containerPort: 9001
              name: health
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 50Mi
      serviceAccountName: {{ $serviceAccountName | quote }}
      tolerations: {{ .Values.portal.tolerations | toJson }}
