{{- if .Values.portal.serviceAccount.create -}}
{{- $component := "portal" -}}
{{- $name := print .Chart.Name "-" .Release.Name "-" $component -}}
{{- $defaultServiceAccountName := ternary $name "default" .Values.portal.serviceAccount.create -}}
{{- $serviceAccountName := default $defaultServiceAccountName .Values.portal.serviceAccount.name -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if not (empty .Values.portal.serviceAccount.gcpWorkloadIdentityProject) -}}
  {{- $gcpProjectID := .Values.portal.serviceAccount.gcpWorkloadIdentityProject }}
  annotations:
    iam.gke.io/gcp-service-account: {{ print $serviceAccountName "@" $gcpProjectID ".iam.gserviceaccount.com" | quote }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name | quote }}
    helm.sh/chart: {{ print .Chart.Name "-" .Chart.Version | replace "+" "_" | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/component: {{ $component | quote }}
  name: {{ $serviceAccountName | quote }}
{{- if not (empty .Values.portal.serviceAccount.gcpWorkloadIdentityProject) -}}
{{- $gcpProjectID := .Values.portal.serviceAccount.gcpWorkloadIdentityProject }}
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: {{ .Chart.Name | quote }}
    helm.sh/chart: {{ print .Chart.Name "-" .Chart.Version | replace "+" "_" | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/component: {{ $component | quote }}
  name: {{ $serviceAccountName | quote }}
spec:
  displayName: Devbot Portal ({{ .Release.Name }})
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  labels:
    app.kubernetes.io/name: {{ .Chart.Name | quote }}
    helm.sh/chart: {{ print .Chart.Name "-" .Chart.Version | replace "+" "_" | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/component: {{ $component | quote }}
  name: {{ print $serviceAccountName "-ksa-link" | quote }}
spec:
  member: {{ print "serviceAccount:" $gcpProjectID ".svc.id.goog[" .Release.Namespace "/" $serviceAccountName "]" | quote }}
  role: roles/iam.workloadIdentityUser
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: {{ $serviceAccountName | quote }}
{{- end -}}
{{- end -}}