apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: api
  name: devbot-api
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/component: api
  type: ClusterIP
