apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    repoURL: https://github.com/arikkfir/infrastructure.git
    path: argocd/server
    targetRevision: HEAD
  destination:
    namespace: argocd
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false # TODO: check if UI shows drift instead
