name: Setup YQ
description: Downloads & installs YQ
inputs:
  version:
    description: yq version
    required: false
    default: v4.7.1
runs:
  using: composite
  steps:
    - name: Install dependencies
      run: apt-get update && apt-get install -y curl
      shell: bash
      env:
        DEBIAN_FRONTEND: noninteractive
    - name: Install
      run: |-
        curl -sSL -o /usr/local/bin/yq "${URL}"
        chmod +x /usr/local/bin/yq
      shell: bash
      env:
        URL: https://github.com/mikefarah/yq/releases/download/${{ inputs.version }}/yq_linux_amd64
