apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: main
resources:
  - ../../base
patches:
  - target: { group: "", version: v1, kind: Namespace }
    patch: |-
      - { op: replace, path: /metadata/name, value: main }
  - target: { group: helm.toolkit.fluxcd.io, version: v2beta1, kind: HelmRelease, name: devbot }
    patch: |-
      - { op: replace, path: /spec/chart/spec/version, value: main-tag }
      - { op: replace, path: /spec/values/ingress/dns/record/name, value: devbot.main.kfirs.com }
  - target: { group: helm.toolkit.fluxcd.io, version: v2beta1, kind: HelmRelease, name: kfirs-com }
    patch: |-
      - { op: replace, path: /spec/chart/spec/version, value: main-tag }
      - { op: replace, path: /spec/values/ingress/dns/record/name, value: www.main.kfirs.com }
