apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: main
resources:
  - namespace.yaml
  - devbot.yaml
patches:
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2beta1
      kind: HelmRelease
      name: devbot
    patch: |-
      - op: replace
        path: /spec/values/ingress/dns/record/name
        value: devbot.main.kfirs.com
      - op: add
        path: /spec/values/api/image
        value: {tag: main-tag}
      - op: add
        path: /spec/values/portal/image
        value: {tag: main-tag}
