apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ""
resources:
  - ../main
patches:
  - target: { group: "", version: v1, kind: Namespace }
    path: patch-namespace.yaml
  - target: { group: helm.toolkit.fluxcd.io, version: v2beta1, kind: HelmRelease, name: devbot }
    path: patch-devbot-helmrelease.yaml
  - target: { group: helm.toolkit.fluxcd.io, version: v2beta1, kind: HelmRelease, name: kfirs-com }
    path: patch-kfirs-com-helmrelease.yaml
