apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: "${ENVIRONMENT}"
resources:
  - ../main
commonLabels:
  app.kubernetes.io/instance: "${ENVIRONMENT}"
patches:
  - target: { group: iam.cnrm.cloud.google.com, version: v1beta1, kind: IAMPolicyMember, name: ksa-link-devbot-api }
    patch: '[ { "op": "add","path": "/spec/member","value": "serviceAccount:arikkfir.svc.id.goog[${ENVIRONMENT}/${ENVIRONMENT}-devbot-api]" } ]'
replacements:
  - source: { group: "", version: v1, kind: Namespace, fieldPath: metadata.name }
    targets:
      - select: { }
        reject:
          - group: ""
            version: v1
            kind: Namespace
        fieldPaths: [ "metadata.name" ]
        options: { delimiter: "-", index: 0, create: false }
      - select: { group: "", version: v1, kind: ServiceAccount }
        fieldPaths: [ "metadata.annotations.[iam.gke.io/gcp-service-account]" ]
        options: { delimiter: "-", index: 0, create: false }
      - select: { group: iam.cnrm.cloud.google.com, version: v1beta1, kind: IAMServiceAccount }
        fieldPaths: [ "spec.displayName" ]
        options: { delimiter: " // ", index: 1, create: false }
