apiVersion: kude.kfirs.com/v1alpha1
kind: Pipeline
resources:
  - https://raw.githubusercontent.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/main/deploy/provider-gcp-plugin.yaml
pipeline:
  - image: ghcr.io/arikkfir/kude/functions/helm
    network: true
    config:
      helm-version: 3.8.1
      args:
        - template
        - secrets-store-csi-driver
        - secrets-store-csi-driver
        - --include-crds
        - --namespace=kube-system
        - --repo=https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
        - --version=1.1.2
        - --values=/workspace/values.yaml
    mounts:
      - secrets-store-csi-driver-values.yaml:values.yaml
  - image: ghcr.io/arikkfir/kude/functions/yq
    config:
      expr: |-
        . |= with(
          select(.apiVersion == "apps/v1" and
                 .kind == "DaemonSet" and
                 .metadata.labels.app == "csi-secrets-store-provider-gcp");
          .spec.template.spec.tolerations = [{ "key": "kfirs.com/workload-nodes", "operator": "Exists" }]
        )
  - image: ghcr.io/arikkfir/kude/functions/yq
    config:
      expr: |-
        . |= with(
          select(.apiVersion == "apps/v1" and
                 .kind == "DaemonSet" and
                 .metadata.labels.app == "csi-secrets-store-provider-gcp");
          .spec.template.spec.affinity = {
            "nodeAffinity": {
              "requiredDuringSchedulingIgnoredDuringExecution": {
                  "nodeSelectorTerms": [
                      {
                        "matchExpressions": [{ "key": "kfirs.com/workload-nodes", "operator": "Exists" }]
                      }
                  ]
              }
            }
          }
        )
  - image: ghcr.io/arikkfir/kude/functions/yq
    config:
      expr: |-
        . |= with(
          select(.apiVersion == "apps/v1" and
                 .kind == "DaemonSet" and
                 .metadata.name == "secrets-store-csi-driver");
          .spec.template.spec.affinity
                             .nodeAffinity
                             .requiredDuringSchedulingIgnoredDuringExecution
                             .nodeSelectorTerms[0]
                             .matchExpressions += [{ "key": "kfirs.com/workload-nodes", "operator": "Exists" }]
        )
  - image: ghcr.io/arikkfir/kude/functions/yq
    config:
      expr: |-
        . |= with(
          select(.apiVersion == "batch/v1" and
                 .kind == "Job" and
                 (.metadata.name == "secrets-store-csi-driver"
                  or .metadata.name == "secrets-store-csi-driver-upgrade-crds"
                  or .metadata.name == "secrets-store-csi-driver-keep-crds"));
          .spec.template.spec.affinity = {
            "nodeAffinity": {
              "requiredDuringSchedulingIgnoredDuringExecution": {
                "nodeSelectorTerms": [
                  { "matchExpressions": [{ "key": "kfirs.com/workload-nodes", "operator": "Exists" }] }
                ]
              }
            }
          }
        )
