apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-server
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    repoURL: https://github.com/arikkfir/infrastructure.git
    path: argocd/server
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: delivery
  syncPolicy:
    automated:
      prune: false
      allowEmpty: false
      selfHeal: false
