apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: slack
spec:
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: flux-system
      namespace: flux-system
    - kind: Kustomization
      name: flux-system
      namespace: flux-system
    - kind: Kustomization
      name: '*'
      namespace: default
  providerRef:
    name: slack
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: github
spec:
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: flux-system
      namespace: flux-system
    - kind: Kustomization
      name: flux-system
      namespace: flux-system
    - kind: Kustomization
      name: '*'
      namespace: default
  providerRef:
    name: github
