apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: all
spec:
  providerRef:
    name: slack
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: flux-system
      namespace: flux-system
    - kind: Kustomization
      name: flux-system
      namespace: flux-system
    - kind: Kustomization
      name: '*'
      namespace: default
