kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: fluxcd-slack
spec:
  template:
    metadata:
      name: fluxcd-slack
      namespace: flux-system
  encryptedData:
    address: AgAIPTKQuqfk88VPJQXhlKVDArb6wZwvTfrANyT0tos5Qh57K0vLSBNdqJnKSjBhNwWnOsQLNfUs1LJEid6QWg4AYal29faItrKSAvZZS0uHH4jBGdoqTeV8jEKO9t1j0TM9REq93FiMJ44PnK4iVxCwGwz3s+kKF8tw+5Vmm95lU4pqS5U4xxVzK/7ajJTrjzBvPjHP0tVH1zJbAeKfiWoqEeigG/PcOoJ7aTIIZbDSgFANrHXpOD36SX9jEO9U9+FQCVr9+IqOCGhoNAYrOVGFhiXQchgx1omOL0L7lBuUR3B4Ij9b8ltbT+t1eCSbmRQMy2OcrBy89CQX4zbpHNcSy209hFxyIxy8Uze/0YPm7FERt9aaL7l8kT5Wl6vtwDfU9hWe1g+oSxvBaPFuP3ldJ9Bvt6eZ/otAoZodANFUlBzRMCvj0Iih7IvwGfS8DJ+DzPgnHNh4wwx2h60JClTXtAZL74HoqzYpBkn2VQbMUAIzj+PfO68X4RMNKae/CFGD8XNuj02hcwYesD9UQLbGAXKNCGyJG2Bk74sNYkOxbBQiqy572A5Eoa+TRSgBTx13PwvSnGY60xHjSS0rRnA/++YgU0X04JlZFw5HMCNpJmWMRNN0qOjehRDpqaT7yeYGu8QEO/AzK0U1wyYgGN1+L5rnH3TXHbcgJnA3CrGnPBQaKxJbFZsb/xMHuS9CjDsVQLHwm0eoNMAScm/rAiHJhhMqgeAO7PmR7R0rj4ZsoRoAbVrqMbfX3ibjnQMeAt+Rbfxir7cExnVcivsim4Nr4XWuIyxOzXSkIJ4/9Jrz
