apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: branches
  namespace: default
spec:
  dependsOn:
    - namespace: system
      name: configuration
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: system
    namespace: system
  path: ./kubernetes/manifests/environments/branches
  prune: true
