apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: slack
spec:
  type: slack
  channel: monitoring
  secretRef:
    name: fluxcd-slack
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: github
spec:
  type: github
  address: https://github.com/arikkfir/infrastructure
  secretRef:
    name: github-runner-pat
