apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: devbot
resources:
  - namespace.yaml
  - gcp-service-account.yaml
  - devbot-deployment.yaml
  - devbot-ingress.yaml
configurations:
  - kustomizeconfig.yaml
