apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: kube-state-metrics
spec:
  interval: 1h
  url: https://kubernetes.github.io/kube-state-metrics
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: prometheus-community
spec:
  interval: 1h
  url: https://prometheus-community.github.io/helm-charts
