apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
spec:
  interval: 5m
  chart:
    spec:
      chart: prometheus
      version: 14.8.1
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
  valuesFrom:
    - kind: ConfigMap
      name: prometheus
      optional: false
      valuesKey: prometheus-values.yaml
