apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prometheus
resources:
  - namespace.yaml
  - helm-repositories.yaml
  - helm-releases.yaml
  - prometheus-ingress.yaml
  - alertmanager-ingress.yaml
configMapGenerator:
  - name: prometheus
    files:
      - prometheus-values.yaml
configurations:
  - kustomizeconfig.yaml
