apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- deployment.yaml
- configuration.yaml
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
    path: gotk-deployment-patches.yaml
  - target:
      group: ""
      version: v1
      kind: Namespace
    path: gotk-namespace-patches.yaml
