apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: 10.3.2
      sourceRef:
        kind: HelmRepository
        name: traefik
  valuesFrom:
    - kind: ConfigMap
      name: traefik
      optional: false
      valuesKey: traefik-values.yaml
