apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
  - namespace.yaml
  - gcp-reserved-ip-address.yaml
  - gcp-load-balancer-dns.yaml
  - helm-traefik-repository.yaml
  - helm-traefik-release.yaml
configMapGenerator:
  - name: traefik
    files:
      - traefik-values.yaml
configurations:
  - kustomizeconfig.yaml
