apiVersion: monitoring.gke.io/v1alpha1
kind: PodMonitor
metadata:
  name: traefik
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: traefik
  podMetricsEndpoints:
  - port: metrics
    path: /metrics
    scheme: http
    interval: 10s
