########################################################################################################################
# WARNING: this file is managed by the "sync-load-balancer.yml" GitHub Actions workflow!
#
# MANUAL EDITS TO SOME OF THE FIELDS HERE WILL BE OVERRIDDEN!
########################################################################################################################

# Reference can be found at: https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
logs:
  general:
    level: WARN
  access:
    enabled: true
    format: json
    bufferingSize: 0
    fields:
      general:
        defaultmode: keep
      headers:
        defaultmode: true
metrics:
  prometheus:
    entryPoint: metrics
service:
  enabled: true
  type: LoadBalancer
  spec:
    loadBalancerIP: 34.141.22.31
    externalTrafficPolicy: Local
  loadBalancerSourceRanges: [217.132.0.0/16]
ingressRoute:
  dashboard:
    enabled: false
resources:
  requests:
    cpu: 100m
    memory: 50Mi
  limits:
    cpu: 300m
    memory: 150Mi
pilot:
  enabled: true
  token: "691f82bf-1c33-4c2e-85c5-53f5f8ed7e33"
  dashboard: true
