apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: f1
resources:
- ../main
commonLabels:
  app.kubernetes.io/instance: replace-helm-with-kustomize
patches:
- patch: '[ { "op": "add","path": "/spec/member","value": "serviceAccount:arikkfir.svc.id.goog[replace-helm-with-kustomize/replace-helm-with-kustomize-devbot-api]"
    } ]'
  target:
    group: iam.cnrm.cloud.google.com
    kind: IAMPolicyMember
    name: ksa-link-devbot-api
    version: v1beta1
replacements:
- source:
    fieldPath: metadata.name
    kind: Namespace
    version: v1
  targets:
  - fieldPaths:
    - metadata.name
    options:
      delimiter: '-'
    select: {}
  - fieldPaths:
    - metadata.annotations.[iam.gke.io/gcp-service-account]
    options:
      delimiter: '-'
    select:
      kind: ServiceAccount
      version: v1
  - fieldPaths:
    - spec.displayName
    options:
      delimiter: ' // '
      index: 1
    select:
      group: iam.cnrm.cloud.google.com
      kind: IAMServiceAccount
      version: v1beta1
images:
- name: europe-docker.pkg.dev/arikkfir/public/arikkfir/devbot/portal
  newTag: 0bba74c
