name: Apply GCP Terraform
on:
  push:
    branches: [main]
    paths:
      - .github/workflows/apply-terraform-gcp.yml
      - terraform/gcp/**
  workflow_dispatch:
concurrency:
  cancel-in-progress: false
  group: terraform/gcp
defaults:
  run:
    shell: bash -eu {0}
env:
  GCP_REGION: europe-west3
  GCP_ZONE: europe-west3-a
jobs:
  terraform:
    runs-on: ubuntu-20.04
    container: ubuntu:21.10
    permissions:
      contents: read
      id-token: write
    timeout-minutes: 60
    steps:
      - run: |-
          apt-get update && apt-get install -y curl python3
          curl -sSL ${GCLOUD_SDK_URL} | tar xz -C /usr/local
          /usr/local/google-cloud-sdk/install.sh --quiet
          ln -s /usr/local/google-cloud-sdk/bin/gcloud /usr/local/google-cloud-sdk/bin/gsutil /usr/local/bin/
        env:
          DEBIAN_FRONTEND: noninteractive
      - uses: google-github-actions/auth@v0.4.0
        with:
          workload_identity_provider: projects/8909046976/locations/global/workloadIdentityPools/github-actions/providers/default
          service_account: infrastructure-github-actions@arikkfir.iam.gserviceaccount.com
      - uses: actions/checkout@v2
#      - uses: google-github-actions/setup-gcloud@master
#        with:
#          project_id: ${{ secrets.GCP_PROJECT_ID }}
#          service_account_key: ${{ secrets.GCP_SA_KEY }}
#          export_default_credentials: true
#          credentials_file_path: gcloud_google_credentials
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.11
          terraform_wrapper: false
      - run: |-
          terraform init -input=false
          terraform validate
          terraform apply -input=false -lock-timeout=180s -auto-approve
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
#          GOOGLE_APPLICATION_CREDENTIALS: ../../gcloud_google_credentials
          TF_VAR_gcp_project: ${{ secrets.GCP_PROJECT_ID }}
          TF_VAR_gcp_region: ${{ env.GCP_REGION }}
          TF_VAR_gcp_zone: ${{ env.GCP_ZONE }}
        working-directory: ./terraform/gcp
