name: Delete Deployment

on:
  pull_request:
    types: [ closed ]

defaults:
  run:
    shell: bash -eu {0}

jobs:

  setup:
    name: Setup
    runs-on: ubuntu-20.04
    outputs:
      branch: ${{ steps.env.outputs.branch }}
      environment: ${{ steps.env.outputs.environment }}
      log_url: ${{ steps.env.outputs.log_url }}
      url: ${{ steps.env.outputs.url }}
    steps:
      - run: |+
          if [[ "${{ github.event_name }}" == "push" ]]; then
            BRANCH="${GITHUB_REF##*/}"
            if [[ "${BRANCH}" == "main" ]]; then
              ENVIRONMENT="production"
              URL="https://www.kfirs.com"
            else
              ENVIRONMENT="${BRANCH}"
              URL="https://www.${ENVIRONMENT}.kfirs.com"
            fi
          else
            BRANCH="${GITHUB_HEAD_REF}"
            ENVIRONMENT="${BRANCH}"
            URL="https://www.${ENVIRONMENT}.kfirs.com"
          fi
          echo "::set-output name=branch::${BRANCH}"
          echo "::set-output name=environment::${ENVIRONMENT}"
          echo "::set-output name=log_url::https://github.com/arikkfir/infrastructure/actions/runs/${{github.run_id}}"
          echo "::set-output name=url::${URL}"
        id: env

  delete-environment:
    name: Delete Environment
    needs: setup
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: echo DELETING ENVIRONMENT NOW!!!
      - uses: strumwolf/delete-deployment-environment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: ${{ needs.setup.outputs.environment }}
