name: Deploy
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/deploy.yml
      - argocd/projects/*.yaml
      - argocd/applications/*.yaml
      - terraform/arikkfir-primary/**
  workflow_dispatch:

defaults:
  run:
    shell: bash -exuo pipefail {0}

env:
  TERRAFORM_VERSION: 1.4.2
  TF_IN_AUTOMATION: true
  GCP_SERVICE_ACCOUNT: gha-arikkfir-infrastructure@arikkfir-primary.iam.gserviceaccount.com
  GCP_WORKLOAD_IDENTITY_PROVIDER: projects/539496846645/locations/global/workloadIdentityPools/github-actions/providers/default
  GCP_CLI_VERSION: 409.0.0

concurrency:
  group: production
  cancel-in-progress: false

permissions:
  id-token: write

jobs:

  format-terraform:
    name: Verify Format
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      - run: terraform fmt -check -recursive -no-color -diff
        working-directory: terraform/arikkfir-primary

  plan-terraform:
    name: Plan Terraform
    needs: format-terraform
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      - uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ env.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.GCP_SERVICE_ACCOUNT }}
      - uses: google-github-actions/setup-gcloud@v1
        with:
          version: ${{ env.GCP_CLI_VERSION }}
      - run: terraform init -input=false
        working-directory: terraform/arikkfir-primary
      - run: terraform plan -input=false -lock-timeout=180s -out tfplan
        working-directory: terraform/arikkfir-primary
      - run: tar -c -j -v -f tfplan.tar.bz2 .terraform .terraform.lock.hcl *.tf tfplan
        working-directory: terraform/arikkfir-primary
      - uses: actions/upload-artifact@v3
        with:
          name: plan
          path: terraform/arikkfir-primary/tfplan.tar.bz2
          if-no-files-found: error
          retention-days: 1

  apply-infrastructure:
    name: Apply Terraform
    needs: plan-terraform
    runs-on: ubuntu-latest
    timeout-minutes: 120
    environment: production
    outputs:
      gke-cluster-name: ${{ steps.apply-terraform.outputs.gke-cluster-name }}
      gke-cluster-location: ${{ steps.apply-terraform.outputs.gke-cluster-location }}
      argocd-installed: ${{ steps.check-argocd.outputs.argocd-installed }}
    steps:
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          terraform_wrapper: false
      - uses: actions/download-artifact@v3
        with:
          name: plan
      - run: tar xjvf tfplan.tar.bz2
      - uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ env.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.GCP_SERVICE_ACCOUNT }}
      - uses: google-github-actions/setup-gcloud@v1
        with:
          install_components: gke-gcloud-auth-plugin
          version: ${{ env.GCP_CLI_VERSION }}
      - run: |
          terraform apply -input=false -lock-timeout=180s -auto-approve tfplan
          echo "gke-cluster-name=$(terraform output -raw gke_cluster_name)" >> $GITHUB_OUTPUT
          echo "gke-cluster-location=$(terraform output -raw gke_cluster_location)" >> $GITHUB_OUTPUT
        id: apply-terraform
      - run: |
          if kubectl get namespace argocd; then
            echo "argocd-installed=true" >> "$GITHUB_OUTPUT"
          else
            echo "argocd-installed=false" >> "$GITHUB_OUTPUT"
          fi
        id: check-argocd

  apply-argocd-server:
    name: Apply ArgoCD Server
    needs: apply-infrastructure
    runs-on: ubuntu-latest
    if: needs.apply-infrastructure.outputs.argocd-installed == 'false'
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ env.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.GCP_SERVICE_ACCOUNT }}
      - uses: google-github-actions/setup-gcloud@v1
        with:
          version: ${{ env.GCP_CLI_VERSION }}
      - uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: ${{ needs.apply-infrastructure.outputs.gke-cluster-name }}
          location: ${{ needs.apply-infrastructure.outputs.gke-cluster-location }}
      - run: |
          curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x /usr/local/bin/argocd
      - run: |
          kubectl apply -k ./argocd/server
          kubectl config set-context --current --namespace=argocd
          kubectl wait --for=jsonpath='{.status.availableReplicas}'=1 --timeout=30m statefulset -l app.kubernetes.io/part-of=argocd
          kubectl wait --for=jsonpath='{.status.readyReplicas}'=1 --timeout=30m statefulset -l app.kubernetes.io/part-of=argocd
          kubectl wait --for=condition=Available=True --timeout=30m deployment -l app.kubernetes.io/part-of=argocd
          kubectl wait --for=condition=Available=True --timeout=30m deployment -l app.kubernetes.io/part-of=argocd-applicationset

          INITIAL_PWD=$(kubectl get secret argocd-initial-admin-secret -oyaml|yq '.data.password'|base64 -d)
          argocd --port-forward login --plaintext --username admin --password "${INITIAL_PWD}"
          argocd --port-forward account update-password --plaintext --current-password "${INITIAL_PWD}" --new-password "${ARGOCD_PASSWORD}"
          kubectl delete secret argocd-initial-admin-secret
        env:
          ARGOCD_PASSWORD: ${{ secrets.ARGOCD_PASSWORD }}

  apply-argocd-resources:
    name: Apply ArgoCD Applications
    needs: [apply-infrastructure, apply-argocd-server]
    if: always() 
      && jobs.apply-infrastructure.result == 'success' 
      && (jobs.apply-argocd-server.result == 'success' || jobs.apply-argocd-server.result == 'skipped')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ env.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.GCP_SERVICE_ACCOUNT }}
      - uses: google-github-actions/setup-gcloud@v1
        with:
          version: ${{ env.GCP_CLI_VERSION }}
      - uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: ${{ needs.apply-infrastructure.outputs.gke-cluster-name }}
          location: ${{ needs.apply-infrastructure.outputs.gke-cluster-location }}
      - run: |
          kubectl apply -f './argocd/projects/*.yaml' --timeout=30m
          #kubectl apply -f './argocd/applications/argocd-server.yaml' --timeout=30m
