name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/deploy.yml
      - "*.tf"

defaults:
  run:
    shell: bash -euo pipefail {0}

env:
  TERRAFORM_VERSION: 1.3.4
  TF_IN_AUTOMATION: true

concurrency:
  group: production
  cancel-in-progress: false

jobs:

  format:
    name: Verify Format
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      - run: terraform fmt -check -recursive -no-color -diff
        id: fmt

  plan:
    name: Plan
    needs: format
    runs-on: ubuntu-latest
    timeout-minutes: 15
#    permissions:
#      contents: 'read'
#      id-token: 'write'
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      - uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: 'projects/arikkfir/locations/global/workloadIdentityPools/github-actions/providers/default'
          service_account: ${{ secrets.GCP_SA_NAME }}
      - uses: google-github-actions/setup-gcloud@v1
        with:
          version: 409.0.0
      - run: terraform init -input=false -no-color
      - run: terraform plan -input=false -lock-timeout=180s -no-color -out tfplan
        id: plan
        env:
          TF_VAR_gcp_region: europe-west3
          TF_VAR_gcp_zone: europe-west3-a
      - run: tar -c -j -v -f tfplan.tar.bz2 .terraform .terraform.lock.hcl *.tf tfplan
      - uses: actions/upload-artifact@v3
        with:
          name: plan
          path: tfplan.tar.bz2
          if-no-files-found: error
          retention-days: 7

#  apply:
#    name: Apply
#    needs: [plan]
#    runs-on: ubuntu-20.04
#    environment:
#      name: production
#    timeout-minutes: 120
#    steps:
#      - uses: hashicorp/setup-terraform@v1
#        with:
#          terraform_version: ${{ env.TERRAFORM_VERSION }}
#      - uses: google-github-actions/auth@v0
#        with:
#          service_account: ${{ secrets.GCP_SA_NAME }}
#          credentials_json: ${{ secrets.GCP_SA_KEY }}
#      - uses: google-github-actions/setup-gcloud@v0
#      - uses: actions/download-artifact@v3
#        with:
#          name: plan
#      - run: tar xjvf tfplan.tar.bz2
#      - run: terraform apply -input=false -lock-timeout=180s -auto-approve -no-color tfplan
#        id: apply
