name: Deployment 2

on:
  issue_comment:
    types:
      - created
  push:
    branches: [ main ]
    paths:
      - .github/workflows/deployment2.yml
      - kubernetes/**
      - terraform/**

defaults:
  run:
    shell: bash -eu {0}

jobs:

  setup:
    name: Setup
    if: >-
      (github.event_name == 'push' && github.ref == 'refs/heads/main') || 
      (github.event.issue.pull_request && github.event.comment.body == '/deploy')
    runs-on: ubuntu-20.04
    outputs:
      branch: ${{ steps.env.outputs.branch }}
      environment: ${{ steps.env.outputs.environment }}
      log_url: ${{ steps.env.outputs.log_url }}
      url: ${{ steps.env.outputs.url }}
    steps:
      - uses: xt0rted/pull-request-comment-branch@v1
        id: pr
        if: github.event.issue.pull_request && github.event.comment.body == '/deploy'
      - run: |+
          if [[ "${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}" == "true" ]]; then
            BRANCH="main"
            ENVIRONMENT="production"
            URL="https://www.kfirs.com"
          else
            BRANCH="${{ steps.pr.outputs.head_ref }}"
            ENVIRONMENT="${{ steps.pr.outputs.head_ref }}"
            URL="https://www.${ENVIRONMENT}.kfirs.com"
          fi
          echo "::set-output name=branch::${BRANCH}"
          echo "::set-output name=environment::${ENVIRONMENT}"
          echo "::set-output name=log_url::https://github.com/arikkfir/infrastructure/actions/runs/${{github.run_id}}"
          echo "::set-output name=url::${URL}"
        id: env

  deploy-terraform-gcp:
    needs: setup
    runs-on: ubuntu-20.04
    environment:
      name: ${{ needs.setup.outputs.environment }}
      url: ${{ needs.setup.outputs.url }}
    defaults:
      run:
        working-directory: ./terraform/gcp
    env:
      TF_IN_AUTOMATION: true
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v0
        with:
          service_account: gha-arikkfir-infrastructure@arikkfir.iam.gserviceaccount.com
          credentials_json: ${{ secrets.GCP_SA_GHA_ARIKKFIR_INFRASTRUCTURE_KEY }}
      - uses: google-github-actions/setup-gcloud@v0
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7
      - run: terraform init -input=false -no-color
      - run: terraform apply -input=false -lock-timeout=180s -auto-approve -no-color
        id: apply
        env:
          TF_VAR_environment: ${{ needs.setup.outputs.environment }}
          TF_VAR_gcp_billing_account: ${{ secrets.GCP_BILLING_ACCOUNT_ID }}
          TF_VAR_gcp_project: ${{ secrets.GCP_PROJECT_ID }}
          TF_VAR_gcp_region: europe-west3
          TF_VAR_gcp_zone: europe-west3-a

