name: Deploy
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/deploy.yml
      - terraform/arikkfir-primary/**
  workflow_dispatch:

defaults:
  run:
    shell: bash -exuo pipefail {0}

env:
  TERRAFORM_VERSION: 1.4.2
  TF_IN_AUTOMATION: true
  GCP_SERVICE_ACCOUNT: gha-arikkfir-infrastructure@arikkfir-primary.iam.gserviceaccount.com
  GCP_WORKLOAD_IDENTITY_PROVIDER: projects/539496846645/locations/global/workloadIdentityPools/github-actions/providers/default
  GCP_CLI_VERSION: 409.0.0

concurrency:
  group: production
  cancel-in-progress: false

permissions:
  id-token: write

jobs:

  format-terraform:
    name: Verify Format
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      - run: terraform fmt -check -recursive -no-color -diff
        working-directory: terraform/arikkfir-primary

  plan-terraform:
    name: Plan Terraform
    needs: format-terraform
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      - uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ env.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.GCP_SERVICE_ACCOUNT }}
      - uses: google-github-actions/setup-gcloud@v1
        with:
          version: ${{ env.GCP_CLI_VERSION }}
      - run: terraform init -input=false
        working-directory: terraform/arikkfir-primary
      - run: terraform plan -input=false -lock-timeout=180s -out tfplan
        working-directory: terraform/arikkfir-primary
      - run: tar -c -j -v -f tfplan.tar.bz2 .terraform .terraform.lock.hcl *.tf tfplan
        working-directory: terraform/arikkfir-primary
      - uses: actions/upload-artifact@v3
        with:
          name: plan
          path: terraform/arikkfir-primary/tfplan.tar.bz2
          if-no-files-found: error
          retention-days: 1

  apply-infrastructure:
    name: Apply Terraform
    needs: plan-terraform
    runs-on: ubuntu-latest
    timeout-minutes: 120
    environment: production
    outputs:
      gke-cluster-name: ${{ steps.apply-terraform.outputs.gke-cluster-name }}
      gke-cluster-location: ${{ steps.apply-terraform.outputs.gke-cluster-location }}
    steps:
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          terraform_wrapper: false
      - uses: actions/download-artifact@v3
        with:
          name: plan
      - run: tar xjvf tfplan.tar.bz2
      - uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ env.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.GCP_SERVICE_ACCOUNT }}
      - uses: google-github-actions/setup-gcloud@v1
        with:
          install_components: gke-gcloud-auth-plugin
          version: ${{ env.GCP_CLI_VERSION }}
      - run: |
          terraform apply -input=false -lock-timeout=180s -auto-approve tfplan
          echo "gke-cluster-name=$(terraform output -raw gke_cluster_name)" >> $GITHUB_OUTPUT
          echo "gke-cluster-location=$(terraform output -raw gke_cluster_location)" >> $GITHUB_OUTPUT
        id: apply-terraform

  apply-fluxcd:
    name: Apply FluxCD
    needs: apply-infrastructure
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ env.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.GCP_SERVICE_ACCOUNT }}
      - uses: google-github-actions/setup-gcloud@v1
        with:
          version: ${{ env.GCP_CLI_VERSION }}
      - uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: ${{ needs.apply-infrastructure.outputs.gke-cluster-name }}
          location: ${{ needs.apply-infrastructure.outputs.gke-cluster-location }}
      - uses: fluxcd/flux2/action@main
        with:
          version: 2.0.0-rc.1
      - run: |
          flux bootstrap github \
            --interval 5m \
            --owner arikkfir \
            --repository delivery \
            --branch main \
            --path clusters/${GKE_CLUSTER_NAME} \
            --personal \
            --reconcile \
            --author-email flux@kfirs.com \
            --author-name "FluxCD Bot" \
            --timeout 30m
        env:
          GKE_CLUSTER_NAME: ${{ needs.apply-infrastructure.outputs.gke-cluster-name }}
          GITHUB_TOKEN: ${{ secrets.DELIVERY_PAT }}
