name: Deploy

on:
  pull_request:
    paths:
      - .github/workflows/deploy.yml
      - *.tf
    types:
      - synchronize
      - opened
      - reopened

defaults:
  run:
    shell: bash -euo pipefail {0}

env:
  GCP_REGION: europe-west3
  GCP_ZONE: europe-west3-a
  TERRAFORM_VERSION: 1.1.7
  TF_IN_AUTOMATION: true
  TF_VAR_gcp_project: ${{ secrets.GCP_PROJECT_ID }}
  TF_VAR_gcp_region: europe-west3
  TF_VAR_gcp_zone: europe-west3-a

jobs:

  tf-fmt:
    name: Terraform Format Verification
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      - run: terraform fmt -check -recursive -no-color -diff | tee tf-format.diff
      - uses: marocchino/sticky-pull-request-comment@v2
        if: always()
        with:
          header: tf-fmt
          path: tf-format.diff
          hide_and_recreate: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
