name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/deploy.yml
      - "*.tf"

defaults:
  run:
    shell: bash -euo pipefail {0}

env:
  TERRAFORM_VERSION: 1.3.4
  TF_IN_AUTOMATION: true
  GCP_WORKLOAD_IDENTITY_PROVIDER: projects/8909046976/locations/global/workloadIdentityPools/github-actions/providers/default
  GCP_CLI_VERSION: 409.0.0
  GCP_REGION: europe-west3
  GCP_ZONE: europe-west3-a

concurrency:
  group: production
  cancel-in-progress: false

jobs:

  format:
    name: Verify Format
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      - run: terraform fmt -check -recursive -no-color -diff

  plan:
    name: Plan
    needs: format
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      - uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ env.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_NAME }}
      - uses: google-github-actions/setup-gcloud@v1
        with:
          version: ${{ env.GCP_CLI_VERSION }}
      - run: terraform init -input=false
      - run: terraform plan -input=false -lock-timeout=180s -out tfplan
        id: plan
        env:
          GITHUB_TOKEN: ${{ secrets.TF_GITHUB_TOKEN }}
          TF_VAR_gcp_region: ${{ env.GCP_REGION }}
          TF_VAR_gcp_zone: ${{ env.GCP_ZONE }}
      - run: tar -c -j -v -f tfplan.tar.bz2 .terraform .terraform.lock.hcl *.tf tfplan
      - uses: actions/upload-artifact@v3
        with:
          name: plan
          path: tfplan.tar.bz2
          if-no-files-found: error
          retention-days: 7

  apply:
    name: Apply
    needs: plan
    runs-on: ubuntu-latest
    timeout-minutes: 120
    permissions:
      contents: write
      id-token: write
    environment: production
    steps:
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      - uses: actions/download-artifact@v3
        with:
          name: plan
      - run: tar xjvf tfplan.tar.bz2
      - uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ env.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_NAME }}
      - uses: google-github-actions/setup-gcloud@v1
        with:
          install_components: gke-gcloud-auth-plugin
          version: ${{ env.GCP_CLI_VERSION }}
      - run: terraform apply -input=false -lock-timeout=180s -auto-approve tfplan
        env:
          GITHUB_TOKEN: ${{ secrets.TF_GITHUB_TOKEN }}
      - uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: primary
          location: ${{ env.GCP_ZONE }}
      - uses: fluxcd/flux2/action@main
      - name: fluxcd bootstrap
        run: |
          flux version --client
          flux bootstrap github --personal \
                                --owner=arikkfir \
                                --repository=infrastructure \
                                --path=flux/clusters/primary \
                                --author-email=flux@kfirfamily.com \
                                --author-name=FluxCD \
                                --branch=main \
                                --commit-message-appendix='[ci skip]'
        env:
          GITHUB_TOKEN: ${{ secrets.TF_GITHUB_TOKEN }}
