name: Deploy Pull Request

on:
  deployment

defaults:
  run:
    shell: bash -eu {0}

env:
  TF_VAR_gcp_billing_account: ${{ secrets.GCP_BILLING_ACCOUNT_ID }}
  TF_VAR_gcp_project: ${{ secrets.GCP_PROJECT_ID }}
  TF_VAR_gcp_region: europe-west3
  TF_VAR_gcp_zone: europe-west3-a

jobs:

  deploy-terraform-gcp:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./terraform/gcp
    env:
      TF_IN_AUTOMATION: true
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v0
        with:
          service_account: gha-arikkfir-infrastructure@arikkfir.iam.gserviceaccount.com
          credentials_json: ${{ secrets.GCP_SA_GHA_ARIKKFIR_INFRASTRUCTURE_KEY }}
      - uses: google-github-actions/setup-gcloud@v0
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7
      - run: terraform init -input=false -no-color
      - run: terraform apply -input=false -lock-timeout=180s -auto-approve -no-color
        id: apply
        env:
          TF_VAR_gcp_billing_account: ${{ secrets.GCP_BILLING_ACCOUNT_ID }}
          TF_VAR_gcp_project: ${{ secrets.GCP_PROJECT_ID }}
          TF_VAR_gcp_region: europe-west3
          TF_VAR_gcp_zone: europe-west3-a
