name: Trigger Pull Request Deployment

on:
  issue_comment:
    types:
      - created

defaults:
  run:
    shell: bash -eu {0}

jobs:

  trigger-deployment:
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '/deploy ') && !contains(github.event.comment.body, '\n')
    runs-on: ubuntu-20.04
    steps:
      - uses: tibdex/github-app-token@v1
        id: token
        with:
          app_id: ${{ secrets.ARIKKFIR_APP_ID }}
          private_key: ${{ secrets.ARIKKFIR_APP_PRIVATE_KEY }}
      - run: |+
          set -x
          cat >request.json <<EOF
          {
            "auto_merge": false, 
            "environment": "$(echo -n '${{ github.event.comment.body }}' | sed -e 's/^\/deploy \(.*\)$/\1/')", 
            "description": "Deploy #${{ github.event.issue.number }}", 
            "ref": "$(curl -sSL -H "${ACCEPT_HEADER}" -H "${AUTH_HEADER}" "${GET_PR_URL}" | jq -r '.head.ref')", 
            "payload": {
              "pull_request": ${{ github.event.issue.number }}
            }
          }
          EOF
          curl -sSL -X POST -H "${ACCEPT_HEADER}" -H "${AUTH_HEADER}" "${POST_DEPLOYMENT_URL}" -d @request.json
        env:
          ACCEPT_HEADER: "Accept: application/vnd.github.v3+json"
          AUTH_HEADER: "Authorization: token ${{ steps.token.outputs.token }}"
          GET_PR_URL: "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.issue.number }}"
          POST_DEPLOYMENT_URL: "https://api.github.com/repos/${{ github.repository }}/deployments"
