name: Trigger Pull Request Deployment

on:
  issue_comment:
    types:
      - created

defaults:
  run:
    shell: bash -eu {0}

jobs:

  trigger-deployment:
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '/deploy ') && !contains(github.event.comment.body, '\n')
    runs-on: ubuntu-20.04
    steps:
      - run: |+
          set -x
          PR_REF=$(curl -sSL -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${GITHUB_TOKEN}" \
                        "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.issue.number }}" | jq -r '.head.ref')
          TARGET_ENV="$(echo -n '/deploy qa02' | sed -e 's/^\/deploy \(.*\)$/\1/')"
          DESCRIPTION="Deploy #${{ github.event.issue.number }}"
          TRANSIENT="false"
          curl -sSL -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${GITHUB_TOKEN}" \
               "https://api.github.com/repos/${{ github.repository }}/deployments" \
               -d "{\"auto_merge\": false, \"environment\": \"${TARGET_ENV}\", \"description\": \"${DESCRIPTION}\", \"ref\":\"${PR_REF}\", \"transient_environment\": ${TRANSIENT}}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
