name: Trigger Pull Request Deployment

on:
  issue_comment:
    types:
      - created

defaults:
  run:
    shell: bash -eu {0}

jobs:

  trigger-deployment:
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '/deploy ')
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/github-script@v6
        with:
          script: |+
            console.log(JSON.stringify(context.issue));
            console.log(JSON.stringify(context.pull_request));
            const pr = github.rest.pulls.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number
            });
            console.log(JSON.stringify(pr));
            const result = github.rest.repos.createDeployment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: pr.head.ref,
                auto_merge: false,
                environment: context.payload.comment.body.match(/^\/deploy (.+)$/)[1],
                description: `Deploy PR#${context.issue.number}`,
                transient_environment: false,
                production_environment: false
            });
            console.log(JSON.stringify(result));
